### ISSUE TITLE
急！完全不能连接Behance（不是慢，是连接不上），其他网站如Pinterest google facebook就没问题

### ISSUE THREAD

**Issue by music7stage** [paradiseduo/ShadowsocksX-NG-R8#63]
急！完全不能连接Behance（不是慢，是连接不上），其他网站如Pinterest google facebook就没问题

**Comment by Marchccc** [comment]
宁不会开全局？

**Comment by paradiseduo** [comment]
规则问题，与软件无关

**Comment by music7stage** [comment]
> 宁不会开全局？

宁该不会以为我开的不是全局吧？不会吧不会吧

**Comment by Marchccc** [comment]
去你妈的你个大傻逼         
            
                
                    
                            
                                
                            
                            
                                剑心
                            
                    
                        
                            
                                    邮箱：0x00gc@gmail.com
                            
                        
                
            
        在2020年09月07日 21:34，music7stage 写道： 



宁不会开全局？



宁该不会以为我开的不是全局吧？不会吧不会吧



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/paradiseduo/ShadowsocksX-NG-R8/issues/63#issuecomment-688329747",

"url": "https://github.com/paradiseduo/ShadowsocksX-NG-R8/issues/63#issuecomment-688329747",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
